services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      Investment__DataJsonFile: /app/data/data.json
      Investment__Repository__Provider: LocalJson
      CashFlow__DataJsonFile: /app/data/data-cashflow.json
      CashFlow__Repository__Provider: LocalJson
    volumes:
      - ./data:/app/data
