# Build stage
FROM node:22-alpine AS build
WORKDIR /app
COPY Financial.Web/package*.json .
RUN npm ci
COPY Financial.Web/ .

ARG API_BASE_URL=http://localhost:3000
RUN echo "API_BASE_URL=${API_BASE_URL}" > .env
RUN npm run build

# Serve stage
FROM nginx:alpine AS final
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
