using System;
using System.Collections.Generic;
using Financial.Domain.Entities;

namespace Financial.Infrastructure.Integrations.GoogleFinancialSupport;

internal readonly record struct AssetClassificationEntry(
    CountryCode Country,
    string LocalTypeCode,
    GlobalAssetClass Class);

internal static class HardcodedAssetClassificationLookup
{
    private static readonly IReadOnlyDictionary<string, AssetClassificationEntry> Entries =
        new Dictionary<string, AssetClassificationEntry>(StringComparer.OrdinalIgnoreCase)
        {
            ["AbbVie"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Aflac Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["AGNC INVESTMENT CORP. (AGNC)"] = new AssetClassificationEntry(CountryCode.UK, "REIT", GlobalAssetClass.RealEstate),
            ["AGNC INVESTMENT CORP. (AGNC) 2 ISA"] = new AssetClassificationEntry(CountryCode.US, "REIT", GlobalAssetClass.RealEstate),
            ["AGREE REALTY CORPORATION (ADC)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["AIEC11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Altria"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Apple Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["ARCHER-DANIELS-MIDLAND COMPANY (ADM)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["AstraSpace"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["AT&T"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["AT&T Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["AUTOMATIC DATA PROCESSING, INC. (ADP)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Bank of Montreal"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["BBAS3"] = new AssetClassificationEntry(CountryCode.BR, "Acoes", GlobalAssetClass.Equity),
            ["BCIA11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Bitcoin"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["BOVA11"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.ETF),
            ["BP"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Brasil Capital 30 Advisory FIC FIA"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["BRCO11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["BRCR11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["British American Tobacco PLC (BATS)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Broadcom"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["BTCI11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["BTLG11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["CANADIAN NATURAL RESOURCES LIMITED (CNQ)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Cardinal Health Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["CATERPILLAR INC. (CAT)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Chevron Corp."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["CHUBB LIMITED (CB)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Cisco Systems"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["CNES11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Commodities"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["CPTS11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["CVBI11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Dahlia Total Return Advisory FIC FIM"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["Ecolab Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["EMERSON ELECTRIC CO. (EMR)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["FRANKLIN RESOURCES, INC. (BEN)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["FTSE100"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["General Dynamics Corp."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["GiltsI"] = new AssetClassificationEntry(CountryCode.UK, "ConventionalGilt", GlobalAssetClass.Bond),
            ["GiltsV"] = new AssetClassificationEntry(CountryCode.UK, "ConventionalGilt", GlobalAssetClass.Bond),
            ["GOLD11"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["Grao ARCA"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["Guepardo Institucional FIC FIA"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["Halliburton"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["HGLG11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["HGRU11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Hix Capital Institucional FIC FIA"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["IBM Corp."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Illinois Tool Works Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["ImpaxEnviro"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Inco"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["Invesco FTSE All-World"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["IP - Participações IPG FIC FIA BDR Nível I"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["iShares USD Bond Fund"] = new AssetClassificationEntry(CountryCode.UK, "Bond", GlobalAssetClass.Bond),
            ["IVVB11"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Fund),
            ["JOHNSON & JOHNSON (JNJ)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["JPMorgan Chase & Co"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["JPMorgan Chase & Co. 2"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["JSRE11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["KFOF11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Kimberly-Clark Corp."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["KLBN4"] = new AssetClassificationEntry(CountryCode.BR, "Acoes", GlobalAssetClass.Equity),
            ["KNCR11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Lloyds Banking"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Lowe's"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Lowe's Companies Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["LTC PROPERTIES, INC. (LTC)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["LVBI11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["MAIN STREET CAP.CP.DL"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["MCCI11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["McDonald's"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["McDonald's Corp."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Medtronic Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["MGFF11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["MGLU3"] = new AssetClassificationEntry(CountryCode.BR, "Acoes", GlobalAssetClass.Equity),
            ["NextEra Energy"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Nucor Corp."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Paramount Global"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["PATL11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["PepsiCo"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["PepsiCo Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["PETR3(ON)"] = new AssetClassificationEntry(CountryCode.BR, "Acoes", GlobalAssetClass.Equity),
            ["PETR4(PF)"] = new AssetClassificationEntry(CountryCode.BR, "Acoes", GlobalAssetClass.Equity),
            ["PIMCO Short-Term High IE00B7N3YW49"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["PIMCO Short-Term High IE00BYXVWC37"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["PORD11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["PPG Industries Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Procter & Gamble"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Procter & Gamble Corp."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Prospect Capital Corp."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["PVBI11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["RBFM11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["RBRF11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["RBRR11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["RBRR11(OLD)"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["RBVA11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Realty Income"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Realty Income Corp."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Realty Income Corp.2"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Reckitt Benckiser Group PLC (RKT)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["RocketLabUSA"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Roper Technologies Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Royal Bank of Canada"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["S&P 500"] = new AssetClassificationEntry(CountryCode.UK, "ETF", GlobalAssetClass.ETF),
            ["S2TA34"] = new AssetClassificationEntry(CountryCode.BR, "Acoes", GlobalAssetClass.Equity),
            ["Shell"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["SPDR S&P UK Dividend"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["SPDR S&P US Dividend"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["SPXB11"] = new AssetClassificationEntry(CountryCode.BR, "ETF", GlobalAssetClass.ETF),
            ["STAG INDUSTRIAL, INC. (STAG)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Starbucks Corporation"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["SYSCO CORPORATION (SYY)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["T. Rowe Price Group Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["TAEE3"] = new AssetClassificationEntry(CountryCode.BR, "Acoes", GlobalAssetClass.Equity),
            ["TASA4"] = new AssetClassificationEntry(CountryCode.BR, "Acoes", GlobalAssetClass.Equity),
            ["Tesla"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Tesla2"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["The Bank of Nova Scotia"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["THE SHERWIN-WILLIAMS COMPANY (SHW)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["TORD11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Toronto-Dominion Bank"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["UK Dividend"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["UKProperty"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Unilever"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["United Parcel Service"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["USTK11"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["VALE3F"] = new AssetClassificationEntry(CountryCode.BR, "", GlobalAssetClass.Unknown),
            ["Vanguard FTSE Developed World UCITS ETF"] = new AssetClassificationEntry(CountryCode.UK, "ETF", GlobalAssetClass.ETF),
            ["Vanguard FTSE Developed World UCITS ETF ISA"] = new AssetClassificationEntry(CountryCode.UK, "ETF", GlobalAssetClass.ETF),
            ["Vanguard S&P 500 (Dist)"] = new AssetClassificationEntry(CountryCode.UK, "ETF", GlobalAssetClass.ETF),
            ["Vanguard S&P 500 UCITS ETF - (USD) Acc ISA"] = new AssetClassificationEntry(CountryCode.UK, "ETF", GlobalAssetClass.ETF),
            ["Vanguard U.K. Gilt UCITS ETF"] = new AssetClassificationEntry(CountryCode.UK, "ETF", GlobalAssetClass.ETF),
            ["Vanguard USD Corporate 1-3 Year Bond UCITS ETF"] = new AssetClassificationEntry(CountryCode.UK, "ETF", GlobalAssetClass.ETF),
            ["VILG11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["Virgin Galactic"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["VISC11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["W. W. Grainger Inc."] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["WALMART INC. (WMT)"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["Warehouse"] = new AssetClassificationEntry(CountryCode.UK, "", GlobalAssetClass.Unknown),
            ["XPCI11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
            ["XPML11"] = new AssetClassificationEntry(CountryCode.BR, "FII", GlobalAssetClass.RealEstate),
        };

    public static bool TryGet(string assetName, out AssetClassificationEntry entry)
    {
        if (string.IsNullOrWhiteSpace(assetName))
        {
            entry = default;
            return false;
        }

        return Entries.TryGetValue(assetName.Trim(), out entry);
    }
}
